### ISSUE TITLE
Extremely slow require time

### ISSUE THREAD

**Issue by mcollina** [reklatsmasters/saslprep#3]
I've done some analysis on why the MongoDB client was adding ~1s to the startup time of my application. It turns out that populating those massive sets is quite expensive.

I think we could possibly use https://github.com/fb55/bitfield or @mafintosh https://github.com/mafintosh/sparse-bitfield to pre-generate a buffer on disk, and then load it up. Maybe https://github.com/mafintosh/sparse-bitfield/issues/1 would help as well.

@reklatsmasters would you be open on a PR in that regard?

See https://github.com/mongodb-js/mongodb-core/pull/355.

**Comment by reklatsmasters** [comment]
As a quick fix i may implement a lazy loading of code points, something like

```js
function allocateCodePoints() { /* ... */ }

const codePoints = null;

function saslprep(/*...*/) {
	if (!Array.isArray(codePoints)) {
		codePoints = allocateCodePoints();
	}
}
```

`Set`, array destructuring are really slow. Probably, it's a good idea to storing that code points in buffers. I will see later `sparse-bitfield` and `bitfield`.

Thanks for feedback, @mcollina!

**Comment by mcollina** [comment]
The problem is `Set`, not array destructuring. Adding things to a `Set`  is still quite expensive (the V8 improved things in latest V8, but it's still heavy).
The idea for the buffer would be to precompute it and store it on disk, then load it up at startup.

**Comment by reklatsmasters** [comment]
@mcollina I've made precomputed code points map file as you suggested. Could you alsо confirm that bug was fixed?

**Comment by mcollina** [comment]
this fixes it for me.
