### ISSUE TITLE
All code points >= 0x10000 invalid due to surrogate pairs

### ISSUE THREAD

**Issue by rossj** [reklatsmasters/saslprep#4]
I believe that the code is supposed to iterate and check individual Unicode code points, however it is currently iterating each UTF-16 wchar value.

Take, for example, emoji U+1F600 😀. I believe this character should be allowed in input, however it results in `Error: Prohibited character` because the code is separately checking the UTF-16 pairs of `[0xd83d, 0xDE00]` as if they were separate code points.

**Comment by reklatsmasters** [comment]
good catch. Anyway, it need to check RFC before.
